metadata:
  labels:
    app: examples
    description: Examples Controller
    title: Quickstart service demo
spec:
  deploy:
    apiFileName: examples-openapi-v3.yaml
    type:
      fwkSpringBoot:
        groupId: com.mercadona.pedper.web-main
        artifactId: example-api
        package: com.mercadona.pedper.api.web-main
        interfacesWithTags: false
